#%RAML 1.0 DataType

uses:
  Library: ../../library.raml

type: Library.Employee
examples:
  # singleEmployeeRequest: !include 
  # bulkEmployeeCreateRequest: !include 


  # example:
  #           {
  #             "ID": "JS-23-01",
  #             "firstName": "John",
  #             "lastName": "Smith",
  #             "middleName": "Alexander",
  #             "DOB": "1995-06-12",
  #             "email": "john.smith@abc.com",
  #             "contactNumber": "+91-9876543210",
  #             "DOJ": "2023-01-15",
  #             "presentAddress": {
  #               "addressLine1": "123, MG Road",
  #               "addressLine2": "Flat 502, Blue Residency",
  #               "zipCode": "411001",
  #               "State": "Maharashtra",
  #               "country": "India"
  #             },
  #             "permanentAddress": {
  #               "addressLine1": "456, Hill View Road",
  #               "addressLine2": "Greenwood Villa",
  #               "zipCode": "411007",
  #               "State": "Maharashtra",
  #               "country": "India"
  #             },
  #             "department": "HR",
  #             "branchLocation": "Pune",
  #             "grade": "C1Y",
  #             "activeStatus": "A"
  #           }