#%RAML 1.0 DataType

uses:
  Library: ../../library.raml

type: array
items: 
  type: Library.Employee
minItems: 1
maxItems: 10
examples:
  singleEmployeeRequest: !include ../../examples/requests/createEmployeeRequest.json
  # bulkEmployeeCreateRequest: !include 