#%RAML 1.0 DataType

uses:
  Library: ../../library.raml

type: Library.Employee | Library.Employee[]
examples:
  singleEmployeeRequest: !include ../../examples/requests/createEmployeeRequest.json
  # bulkEmployeeCreateRequest: !include 