#%RAML 1.0 DataType

uses:
  Library: ../../library.raml

type: Library.Department
properties:
  deptCode:
    required: false !imp

  deptName?:  string

example: !include ../../examples/requests/updateDepartmentRequest.json