#%RAML 1.0
title: sys-employee-api

baseUri: http://localhost:8081/api

description: this is a system api which does a crud operation on mysql datadase

# uses:

types:
  CreateEmployeeResponse: !include /dataTypes/responses/create-employee-response.raml
  GetEmployeeResponse: !include /dataTypes/responses/get-employees-response.raml

/employees:
  post:
    body:
      application/json:
        # type: !include /employee-request-dataType.raml            
    responses:
      201:
        body:
          application/json:
            type: EmployeeResponse
      500:
        body:
          application/xml:
            type: object
            properties:
              status:
                type: integer
                required: true
                example: 500
              message:
                type: string
                required: true
                example: "Internal Server Error"
            example:
              {
                  "status": 500,
                  "message": “Internal Server Error”
              }
  put:
    body:
      application/xml:
        type: object
        xml:
          name: employee
        properties:
          employeeID:
            required: true
            type: integer
            example: 100
          employeeStatus:
            required: true
            type: string
            example: "A"
        example:
          <?xml version="1.0" encoding="UTF-8"?>
          <employee>
            <employeeID>333</employeeID>
            <employeeStatus>A</employeeStatus>
          </employee>
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              status:
                type: integer
                required: true
                example: 200
              message:
                type: string
                required: true
                example: "Updated"
            example:
              {
		              "status": 200,
                  "message": “Success”
		          }            
      500:
        body:
          application/xml:
            type: object
            xml:
              name: response
            properties:
              status:
                type: integer
                required: true
                example: 500
              message:
                type: string
                required: true
                example: "Internal Server Error"
            example:
              <?xml version="1.0" encoding="UTF-8"?>
              <response>
                <status>500</status>
                <message>Internal Server Error</message>
              </response>
  get:
    queryParameters:
      empid:
        required: true
        type: integer
        example: 32432
    responses:
      200:
        body:
          application/json:
            type: GetEmployeeResponse
            # properties:
            #   status:
            #     type: integer
            #     required: true
            #     example: 201
            #   message:
            #     required: true
            #     type: string
            #     example: "created"
            # example:
            #   {
		        #       "status": 200,
            #       "message": “Success”
		        #   }
      500:
        body:
          application/xml:
            type: object
            properties:
              status:
                type: integer
                required: true
                example: 500
              message:
                type: string
                required: true
                example: "Internal Server Error"
            example:
               {
		              "status": 500,
                  "message": “Internal Server Error”
		          }
  delete:
    responses:
      200:
        body:
          application/json:
            type: object
            properties:
              status:
                type: integer
                required: true
                example: 200
              message:
                type: string
                required: true
                example: "Success"
            example:
              {
		              "status": 200,
                  "message": “Success”
		          }
      500:
        body:
          application/json:
            type: object
            properties:
              status:
                type: integer
                required: true
                example: 500
              message:
                type: string
                required: true
                example: "Internal Server Error"
            example:
              {
		              "status": 500,
                  "message": “Internal Server Error”
		          }
# /update-emp:
#   put:
#     body:
#       application/xml:
#         type: object
#         xml:
#           name: employee
#         properties:
#           employeeID:
#             required: true
#             type: integer
#             example: 100
#           employeeStatus:
#             required: true
#             type: string
#             example: "A"
#         example:
#           <?xml version="1.0" encoding="UTF-8"?>
#           <employee>
#             <employeeID>333</employeeID>
#             <employeeStatus>A</employeeStatus>
#           </employee>
#     responses:
#       200:
#         body:
#           application/json:
#             type: object
#             properties:
#               status:
#                 type: integer
#                 required: true
#                 example: 200
#               message:
#                 type: string
#                 required: true
#                 example: "Updated"
#             example:
#               {
# 		              "status": 200,
#                   "message": “Success”
# 		          }            
#       500:
#         body:
#           application/xml:
#             type: object
#             xml:
#               name: response
#             properties:
#               status:
#                 type: integer
#                 required: true
#                 example: 500
#               message:
#                 type: string
#                 required: true
#                 example: "Internal Server Error"
#             example:
#               <?xml version="1.0" encoding="UTF-8"?>
#               <response>
#                 <status>500</status>
#                 <message>Internal Server Error</message>
#               </response>

# /get-emp:
#   get:
#     queryParameters:
#       empid:
#         required: true
#         type: integer
#         example: 32432
#     responses:
#       200:
#         body:
#           application/json:
#             type: object
#             properties:
#               status:
#                 type: integer
#                 required: true
#                 example: 201
#               message:
#                 required: true
#                 type: string
#                 example: "created"
#             example:
#               {
# 		              "status": 200,
#                   "message": “Success”
# 		          }
#       500:
#         body:
#           application/xml:
#             type: object
#             properties:
#               status:
#                 type: integer
#                 required: true
#                 example: 500
#               message:
#                 type: string
#                 required: true
#                 example: "Internal Server Error"
#             example:
#                {
# 		              "status": 500,
#                   "message": “Internal Server Error”
# 		          }

# /delete-emp/{employeeID}/{employeeName}:
#   delete:
#     responses:
#       200:
#         body:
#           application/json:
#             type: object
#             properties:
#               status:
#                 type: integer
#                 required: true
#                 example: 200
#               message:
#                 type: string
#                 required: true
#                 example: "Success"
#             example:
#               {
# 		              "status": 200,
#                   "message": “Success”
# 		          }
#       500:
#         body:
#           application/json:
#             type: object
#             properties:
#               status:
#                 type: integer
#                 required: true
#                 example: 500
#               message:
#                 type: string
#                 required: true
#                 example: "Internal Server Error"
#             example:
#               {
# 		              "status": 500,
#                   "message": “Internal Server Error”
# 		          }

                  
              
        
              
                  
                  
              
              
              
              

           

          