#%RAML 1.0
title: sys-employee-api

# baseUri: http://localhost:8081/api

description: this is a system api which does a crud operation on snowflake database

uses:
  Library: library.raml


types:
  CreateEmployeeRequest : !include dataTypes/requests/createEmployeeRequest.raml
  UpdateEmployeeRequest:  !include dataTypes/requests/updateEmployeeRequest.raml

  CreateEmployeeResponse: !include dataTypes/responses/createEmployeeResponse.raml
  GetEmployeeResponse: !include dataTypes/responses/getEmployeeResponse.raml

/employees:
  post:
    is: [Library.ErrorResponse]
    body:
      application/json: CreateEmployeeRequest

    responses:
      201:
        body:
          application/json: CreateEmployeeResponse

  get:
    is: [Library.ErrorResponse]
    queryParameters:
      ID:
        required: false
        type: string
        example: "JS-23-01"
      firstName:
        type: string
        required: false
        example: "John"
      email:
        required: false
        type: string
        example: "john.smith@abc.com"
      department:
        required: false
        type: string
        enum: [TR,MR,HR,SR,AR,IR,PR]

    responses:
      200:
        body:
          application/json: GetEmployeeResponse

  
  /{ID}:
    uriParameters:
      ID: Library.ID

    put:
      is: [Library.ErrorResponse]
      body:
        application/json: UpdateEmployeeRequest
      responses:
        200:
          body:
            application/json: Library.Response

    delete:
      is: [Library.ErrorResponse]
      responses:
        200:
          body:
            application/json: Library.Response