#%RAML 1.0 DataType

uses:
  Library: ../../library.raml

types:
  Response: Library.

type: array
items: 
  type: Library.Employee
  properties:
    ID: 
      type: string
      pattern: ^\w{2,3}\-\d{5,10}$
      example: HR-00125

example: !include ../../examples/responses/getEmployeeResponse.json