#%RAML 1.0 Library

types:
  Employee:
    type: object
    properties:
      dob: date-only
      dateOfJoining: date-only
      gender:
        type: string
        enum:
          - Female
          - male
          - others
      branch: string